sudo: required

services:
  - docker

install:
  - docker build -t dnscrypt-wrapper-docker .

script:
  - docker run --interactive --tty dnscrypt-wrapper-docker --version
  - docker run --interactive --tty --rm --volume $KEYDIR:/etc/dnscrypt-wrapper/cert -w /etc/dnscrypt-wrapper/cert dnscrypt-wrapper-docker --gen-provider-keypair | tee /tmp/gen-provider-keypair.log
  - PUBLIC_KEYPAIR_FINGERPRINT=$(egrep 'Public key fingerprint: ' /tmp/gen-provider-keypair.log | sed 's/Public key fingerprint: //')
  - echo $PUBLIC_KEYPAIR_FINGERPRINT
