sudo: required

services:
  - docker

env:
  global:
    - HKEYDIR=/tmp/dnscrypt-wrapper/keys # Directory for keys on host
    - CKEYDIR=/opt/dnscrypt-wrapper/etc/keys # Directory for keys in container

install:
  - docker build -t dnscrypt-wrapper-docker .
  - rm -rf $HKEYDIR
  - mkdir -p $HKEYDIR

script:
  - docker run --interactive --tty --rm dnscrypt-wrapper-docker --version
  - docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscrypt-wrapper-docker --gen-provider-keypair
  - stat -t $HKEYDIR/public.key
  - stat -t $HKEYDIR/secrect.key
  - docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscrypt-wrapper-docker --gen-crypt-keypair
  - stat -t $HKEYDIR/crypt_secret.key
  - docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscrypt-wrapper-docker --gen-cert-file
  - stat -t $HKEYDIR/dnscrypt.cert
